### ISSUE TITLE
怎么设置头像

### ISSUE THREAD

**Issue by NICHX** [LychApe/DreamCat#1]
如图，头像在哪里设置
![QQ截图20201101114754](https://user-images.githubusercontent.com/24547848/97794701-38dee000-1bf5-11eb-9a8a-2b58bebf3e55.png)

**Comment by HanFengA7** [comment]
> 如图,头像在哪里设置
> ![QQ截图20201101114754](https://user-images.githubusercontent.com/24547848/97794701-38dee000-1bf5-11eb-9a8a-2b58bebf3e55.png)

头像在(网站外观->设置外观->站点 LOGO 地址)设置
