### ISSUE TITLE
求助，Lighttpd怎么在启用HTTPS时强制禁用HTTP/2.0

### ISSUE THREAD

**Issue by 1Q23LYC45** [LychApe/DreamCat#128]
安装了DreamCatV3主题。不开https，一切正常。  
打开https（用的可信的权威签名证书），BUG出现：  
本机访问啥问题没有，一用其他设备打开网站，就会出现css和js资源加载不了。关掉https后再次恢复正常。控制台输出一堆400badrequest。查看服务器日志，有几个可疑行：
```
127.0.0.1 1q23l.ftp.sh - [01/Oct/2023:13:42:34 +0800] "PRI * HTTP/2.0" 100 502 "-" "-"
127.0.0.1 - - [01/Oct/2023:13:42:35 +0800] "GET  HTTP/2.0" 400 345 "-" "-"
```
可以看出，get http/2.0中间链接没了
求，如何干掉HTTP2.0，并同时启用HTTPS？

**Comment by 1Q23LYC45** [comment]
自己弄好了，花了半天做了一套Nginx配置文件。现在正常了

**Comment by P3R5T7U9** [comment]
> 自己弄好了，花了半天做了一套Nginx配置文件。现在正常了

抱歉打扰了，近期正想搭建个人博客，为选择哪款主题在github 上翻找半天，偶然翻到这个主题仓库，看了下实例截图，感觉还不错，决定安装这款主题，但随之也遇到老哥你前几天开的这条issue反馈的问题，看老哥你最后回复说花半天做了配套的Nginx文件，麻烦老哥分享下自制的Nginx配置文件么？？
(小声：目前处于学习Nginx初级阶段，尚未达到制作完整的配置文件水平，这不看到老哥你你开的这条issue后，想着趁老哥你之后如能分享对DreamCatV3 主题配套的Nginx配置文件，也学习下Nginx进阶姿势)

**Comment by 1Q23LYC45** [comment]
就是套通用的php配置，需要php-fpm和nginx，自己搭建下就行。实际上不比宝塔面版更便捷。不过我手机没root安装不了宝塔，也没云服务器。这个配置不在默认目录/etc/nginx，因为我需要用mt管理器编辑网站。 

 https://pan.95bl.com/s/oBWSy
自己改一下里面的路径就行。  
root   /sdcard/nginx/htdocs;改成typecho网站根目录
fastcgi_pass   unix:/data/data/com.termux/files/usr/var/run/php-fpm.sock;  
把unix后面改成你服务器的php-fpm监听端口或者Socket都行
access_log和error_log路径随意。只要你能方便访问的位置就行  
注意所有行后面不要丢英文半角分号。

**Comment by 1Q23LYC45** [comment]
启动命令nginx -c <nginx.conf绝对路径 >
停止命令nginx -c <nginx.conf绝对路径 >
本人也是个nginx新手，见谅

**Comment by 1Q23LYC45** [comment]
https支持：把nginx.conf下面https server注释下面的改成差不多这样就行了。还是一样，请自己改下文件路径
```
    server {
        listen       443 ssl;
        #server_name  localhost;
        ssl_certificate      /sdcard/nginx/typecho.certificate.crt;
        ssl_certificate_key  /sdcard/nginx/typecho.private.key;
    #    ssl_session_cache    shared:SSL:1m;
    #    ssl_session_timeout  5m;
    #    ssl_ciphers  HIGH:!aNULL:!MD5;
    #    ssl_prefer_server_ciphers  on;
        root   /sdcard/nginx/htdocs;
        index  index.html index.htm index.php;
        location ~ \.php?.*$ {
            #try_files $uri =404;
            fastcgi_pass   unix:/data/data/com.termux/files/usr/var/run/php-fpm.sock;
            #fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;
            include        fastcgi_params;
        }
```

**Comment by 1Q23LYC45** [comment]
送你一个知乎大佬写的配置优化教程，我认为写的还不错。网盘里我发的那个我加上了php，和MineType（不加上，CSS和JS有时会不加载），其他只是基础配置。
https://zhuanlan.zhihu.com/p/651514719

另外，如果部分网站源码要求强制伪静态/URL重写，不配置打不开的，nginx.conf中找到server段落，加上这个就行，还是别忘了如果缺少分号就加上分号，不过大括号后面不用加分号。
```
    location / {  
	try_files $uri $uri/ /index.php$is_args$query_string;  
    }
```
