### ISSUE TITLE
安装3.0主题后HTTPS安全检测降为B级

### ISSUE THREAD

**Issue by 1Q23LYC45** [LychApe/DreamCat#129]
安装最新版DreamCat主题后，亚洲诚信HTTPS安全检测结果由A+下降为B，提示如下：1. 主页面引用了不安全的HTTP资源，降级为B。手动替换所有HTTP链接改为HTTPS之后恢复。

求更新，把所有HTTP外链引用改成HTTPS。

**Comment by HanFengA7** [comment]
OK合并了，非常感谢！
