### ISSUE TITLE
图片定制

### ISSUE THREAD

**Issue by dingiso** [LychApe/DreamCat#13]
非常好的theme，非常感谢作者的辛勤付出，接着上一issue的内容
我希望可以自己定制每一篇博客显示的图片，或者自动选择文章中markdown嵌入的图片
希望下一个版本可以实现这样的功能

**Comment by HanFengA7** [comment]
在附件中上传图片即可定制每一篇博客显示的图片
附件->选择文件上传->完成

**Comment by HanFengA7** [comment]
### 1. 若你要修改主题自带的随机图片内容

> 你可以在这个文件夹下修改成自己所需的图片
`DreamCat/src/img/OER/`

### 2. 若你要改主题自带的随机图片为外链
> 你可以修改这个文件的代码
(1)`DreamCat/functions.php `
(2)`/** 随机图片 **/  `
`$imgurl = THEME_URL . "/usr/themes/DreamCat/src/img/OER/"`
**THEME_URL**  改为  **"https://xxx.xxx.com"**

### 3. 若你要使文章列表中指定的文章显示成所需要的图片

> 在附件中上传图片即可定制每一篇博客显示的图片
附件->选择文件上传->完成
例：<img src="https://dreamcat.lychape.cn/usr/uploads/2021/02/2225276477.png">

**Comment by dingiso** [comment]
好的，谢谢您，我会根据实际修改我的附件的
