### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by zengjunh** [LychApe/DreamCat#14]
当页面处于最下方时，点击最后一个评论者的头像，会发生无法使用滚轮，以及旁边的滚动条控制页面的情况。

但好像只有点击 没有内容的头像（灰色小人头像） 会出现这种情况

情况在视频中了。

https://user-images.githubusercontent.com/52186476/130754584-923a9af4-7009-440a-a8fb-a6486f66b775.mp4

**Comment by CornWorld** [comment]
据十几天前观察, 这个情况出现原因为: 评论者头像带有一个#的URL属性, 点击后会进行页面加载  
众说周知, 加载页面的时候会卡住DOM, 如果再加上网络传输不良, 会导致DOM长期卡死而出现上述情况  


(上述仅仅为个人观察)

**Comment by CornWorld** [comment]
此问题长期未回复，予以关闭。
This issue has not been committed for a long time so it will be set to closed.
