### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by FREE-U** [LychApe/DreamCat#159]
![Screenshot_2024_0809_114631](https://github.com/user-attachments/assets/43fce0cb-668f-4196-8269-dce1fcb8e9cf)

在设置中调整CDN为本地解决

![Screenshot_2024_0809_115058](https://github.com/user-attachments/assets/73644db5-be0e-4f15-a795-82c154992873)

**Comment by CornWorld** [comment]
https://github.com/LychApe/DreamCat/issues/157

目前仍然有问题吗？
