### ISSUE TITLE
首页顶部报错Undefined variable

### ISSUE THREAD

**Issue by GaoShin** [LychApe/DreamCat#4]
应用主题之后重新打开首页，顶部报错：
Notice: Undefined variable: options in /var/www/typecho/usr/themes/DreamCat/functions.php on line 4
Notice: Trying to get property 'siteUrl' of non-object in /var/www/typecho/usr/themes/DreamCat/functions.php on line 4
Notice: Undefined variable: options in /var/www/typecho/usr/themes/DreamCat/functions.php on line 4
Notice: Trying to get property 'rootUrl' of non-object in /var/www/typecho/usr/themes/DreamCat/functions.php on line 4
Notice: Undefined variable: options in /var/www/typecho/usr/themes/DreamCat/functions.php on line 4
Notice: Trying to get property 'themeUrl' of non-object in /var/www/typecho/usr/themes/DreamCat/functions.php on line 4

**Comment by CornWorld** [comment]
请问能否提供一下使用的版本？
最近我们进行了多次修改，可能是因为版本问题导致的。
建议尝试更新到最新的版本，并提供出现此错误的版本号（最好是commit id）。

**Comment by GaoShin** [comment]
commit id:8d9ce1019c775a6a87add415308ff871473e2793
将主机更换到境内服务器然后换了个端口，就无法再次复现此问题，目前首页不再报错
另外，如果首页页面处于顶端，刷新页面后页面会有概率向下滚动一段距离，请问这个是bug还是新功能？

**Comment by HanFengA7** [comment]
刷新页面后页面会有概率向下滚动一段距离是新功能
