### ISSUE TITLE
建议：使用 Git LFS 存储库文件

### ISSUE THREAD

**Issue by CornWorld** [LychApe/DreamCat#49]

**Comment by CornWorld** [comment]
https://github.com/LychApe/DreamCat/tree/InsiderPrieview_LFS

**Comment by CornWorld** [comment]
@HanFengA7 是否考虑直接对 InsiderPreview 做此操作

**Comment by HanFengA7** [comment]
yes

**Comment by CornWorld** [comment]
因为 Github LFS 下载带宽过小，故关闭此 issue。
