### ISSUE TITLE
移动端点击侧边栏的 DreamCat 后阴影不会自动消失

### ISSUE THREAD

**Issue by chengziorange** [LychApe/DreamCat#5]
复现方法：点击侧边栏的 DreamCat 信息，然后点击“知道啦”，之后页面一直蒙着一层暗色，点击任意位置才会收起侧边栏并恢复正常。

**Comment by HanFengA7** [comment]
感谢反馈，已确认BUG，正在修复。
非常感谢您对DreamCat的支持！

**Comment by HanFengA7** [comment]
己完成修复
