### ISSUE TITLE
功能建议: 文章页面添加“编辑“按钮以及增加一个"以内容代替图片"的选项

### ISSUE THREAD

**Issue by AlwaysKing** [LychApe/DreamCat#9]
1. 在文章的内容页增加一个”编辑“按钮，点击后直接转至后台此文章的编辑页。
2. 在设置中增加一个 ”以内容代替图片“ 的配置项，当开启此选项的时候, 首页的时间线展示的文章 不在以 图片+ 标题的方式展示，而是改为 标题+内容 的方式展示

**Comment by HanFengA7** [comment]
近期会考虑添加 感谢反馈

**Comment by HanFengA7** [comment]
当前建议已列入2.0开发计划中，将在下一个测试版加入

**Comment by HanFengA7** [comment]
当前功能已完成开发
